services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $configFolder: "%swagger.config_folder%"
      $docsFolder: "%kernel.project_dir%/public/api/"

  StfalconStudio\SwaggerBundle\:
    resource: '../../{Command,Config,Generator}'
