language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

php:
  - '7.3'
  - '7.4'

env:
  - SYMFONY_VERSION=4.4.*
  - SYMFONY_VERSION=5.0.*

before_install:
  - composer self-update
  - composer require --no-update symfony/symfony "$SYMFONY_VERSION"

install:
  - composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpcs ./ -p --encoding=utf-8 --extensions=php --ignore="vendor|Tests" --standard=./vendor/escapestudios/symfony2-coding-standard/Symfony
  - ./vendor/bin/phpstan analyse -l 8 --no-progress -c phpstan.neon ./
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - genvaldartem@gmail.com
