language: php

sudo: false

php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  - SYMFONY_VERSION=4.3.*

before_install:
  - composer self-update
  - composer require --no-update symfony/symfony "$SYMFONY_VERSION"

install:
  - composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpcs --standard=phpcs.xml
  - ./vendor/bin/phpstan analyse -l 7 --no-progress -c phpstan.neon ./
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $COMPOSER_CACHE_DIR

notifications:
  email:
    - genvaldartem@gmail.com
